name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure and build
        run: |
          rm -rf build
          cmake -B build -S .
          cmake --build build -j $(nproc)

      - name: Run unit tests
        run: |
          ./build/test_filters
          ./build/test_data_store
