name: Build & push multi-arch image

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/hnswlib_server
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}},value={{tag}}
          type=sha,format=short
          type=ref,event=branch

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        cache-from: type=gha
        cache-to:   type=gha,mode=max
